// The gated pricing-guide PDF (audit item 14). The chapters stay open
// and crawlable at /guides — only the compiled PDF sits behind the
// capture form, served from an unguessable path under /downloads/
// (which robots.txt disallows). Standard gated-asset practice: the gate
// is the trade of an email for a convenience, not a content wall.
//
// The file is generated by `pnpm guide:pdf` (scripts/build-pricing-guide.mts)
// from the same rate card and quote engine the site renders — regenerate
// it at each quarterly rate review alongside RATES_UPDATED.
export const GUIDE_PDF_PATH =
  "/downloads/0KidHPNLdxOF6Aj1Hw2sTJnd/jetnine-charter-pricing-guide-2026.pdf";

export const GUIDE_PDF_TITLE = "The JetNine Charter Pricing Guide (2026)";
