-- One-click unsubscribe for empty-leg alert emails.
--
-- Stored in plain text, unlike the confirmation tokens next to it, and
-- the asymmetry is deliberate: a confirmation token grants consent, so
-- anyone reading a backup could subscribe a stranger and it is kept only
-- as a hash. An unsubscribe token only withdraws consent. The worst
-- someone can do with a leaked one is stop mail that the recipient can
-- restart from the form, so it fails in the safe direction — and it has
-- to be readable at send time, because the cron writes the link into
-- every alert long after the row was created.
--
-- Long-lived on purpose: the link has to keep working in a message
-- someone finds in their archive a year later.

-- Generated by the database so a row cannot exist without one. That
-- removes the failure where an alert goes out with no way to stop it
-- because some code path forgot to mint a token. 24 random bytes as hex
-- is 192 bits and needs no URL escaping.
alter table public.empty_leg_watchlists
  add column "unsubscribe_token" text not null
    default encode(gen_random_bytes(24), 'hex');

create unique index "empty_leg_watchlists_unsubscribe_uq"
  on public.empty_leg_watchlists ("unsubscribe_token");
